### ISSUE TITLE
Traducción de finalwords.md a Español (Translate finalwords.md to spanish)

### ISSUE THREAD

**Issue by juanluischaurant** [the-road-to-learn-react/the-road-to-learn-react-spanish#4]
Bienvenido a The Road to Learn React, una iniciativa en varios idiomas que busca enseñar React a todo aquel que quiera aprender.

"Issue" creado especialmente para participantes del Hacktoberfest que son nuevos contribuyentes en proyectos de código abierto.

**Simplemente, tienes que traducir al Español el archivo "finalwords.md" y hacer la "pull-request" al repositorio.**
 
Si necesitas ayuda, no dudes en preguntar.

¡Que te diviertas!

**Comment by mariogmz** [comment]
Tomando este issue!

**Comment by juanluischaurant** [comment]
Completado por @Draier
