### ISSUE TITLE
Traducir foreword.md a Español / Translate foreword.md to Spanish

### ISSUE THREAD

**Issue by juanluischaurant** [the-road-to-learn-react/the-road-to-learn-react-spanish#8]
Bienvenido a The Road to Learn React, una iniciativa en varios idiomas que busca enseñar React a todo aquel que quiera aprender.

"Issue" creado especialmente para participantes del Hacktoberfest que son nuevos contribuyentes en proyectos de código abierto.

Simplemente, tienes que traducir al Español el archivo "foreword.md" y hacer la "pull-request" al repositorio (puedes traducir solo una parte o el documento completo, toda ayuda es bienvenida).

Si necesitas ayuda, no dudes en preguntar.

¡Que te diviertas!

**Comment by gerardosandoval** [comment]
Tomaré este issue 👍

**Comment by juanluischaurant** [comment]
> 
> 
> Tomaré este issue +1

Genial @gerardosandoval ¡Bienvenido!

**Comment by juanluischaurant** [comment]
Completada por @gerardosandoval
